### ISSUE TITLE
Calling parseInt with a empty string as argument can lead to unexpected behaviour.

### ISSUE THREAD

**Issue by JavaDerg** [the-furry-hubofeverything/MineSweeperJS#4]
https://github.com/the-furry-hubofeverything/MineSweeperJS/blob/b790b22cebfa67923e0305b28810f5d095413c98/res/main.js#L38
Calling parseInt with a empty string will result in NaN and comparing that to any number will always equate in false.
I suggest checking for string lenght.

**Comment by the-furry-hubofeverything** [comment]
But that is the entire point. If the box has no number, it is 0, so therefore it is false, and this is expected behavior. 

Change it if you want, but I'm closing this issue.

**Comment by JavaDerg** [comment]
The point is the code is vague and can lead to unwanted behaviour easily on changes.
The code is unclear and the comparison useless.
Check for `=== NaN` instead.
